version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: Docker Hub Login
                command: |
                    docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
            - run:
                name: Docker Image Build - Web Api
                command: |
                    if [ "${CIRCLE_BRANCH}" == "development" ]; then
                        docker build -f api/env/Dockerfile.dev -t fecaps/financial_control_webapi:development .
                    elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                        docker build -f api/env/Dockerfile -t fecaps/financial_control_webapi:production .
                    fi
            - run:
                name: Docker Hub Deploy - Web Api
                command: |
                    if [ "${CIRCLE_BRANCH}" == "development" ]; then
                        docker push fecaps/financial_control_webapi:development
                    elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                        docker push fecaps/financial_control_webapi:production
                    fi
