service: ${env:SERVICE}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource: arn:aws:dynamodb:${env:REGION}:${env:ACCOUNT_ID}:table/${env:EXPENSES_CATEGORIES_TABLE}

plugins:
  - serverless-dotenv-plugin

functions:
  get-expenses:
    handler: handlers/get-expenses.handler
    description: Financial Control API - Get All Expenses
    events:
      - http:
         path: expenses
         method: get

  get-categories:
    handler: handlers/get-expenses-categories.handler
    description: Financial Control API - Get All Categories
    events:
      - http:
         path: categories
         method: get

resources:
  Resources:
    expensesCategoriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: expenses_categories
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
